### PR TITLE
Use first media URL as feed URL fallback (fixes #252)

### LINKED ISSUE #252: Problem with a feed (5-4 Pod)
**Feed URL**
https://feeds.megaphone.fm/WWO5591736705

**Add-on version**
2.8

**Describe the bug**
This feed displays in the browser window (feed preview), but when added to the bookmark bar the folder remains empty, even on refresh. 

Firefox 77.0.1

### PR DESCRIPTION
**Pull request by evilpie**
I see you added a fallback using the <guid> in
40c1c7442517dea823f0ba40ee4c8b5af4bd3609.
That <guid isPermanent=false> should not be treated as a URL, so I think
it makes sense to use it as a last resort.
For this feeds this didn't even work, because siteUrl is null, so the
new URL constructor fails ...

### CODE REVIEW

File: shared/feed-parser.js [hunk 1]
```diff
@@ -110,6 +110,11 @@ const FeedParser = {
       if (!url) {
         url = getTextFromElement("guid:not([isPermaLink='false'])", item);
       }
+      if (!url) {
+        if (media && media.length) {
+          url = media[0].url;
+        }
+      }
```
Comment (nt1m) [inline shared/feed-parser.js:117]: Wdyt of:

```suggestion
      if (!url && media && media.length) {
        url = media[0].url;
      }
```

Both works either way :)
